services:
  flask:
    container_name: flask
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

volumes:
  db_data:
