services:
  flask:
    container_name: flask
    image: alashshrestha/todo-flask
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    container_name: db
    image: alashshrestha/todo-db
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
